name: MonkeyPlugin
main: NomarTheHero.MonkeyPlugin
version: 0.1
commands:
  ranks:
    description: Links to the page with ranks
  shop:
    description: Links to the server store
  website:
    description: Links to the website
  faq:
    description: Links to the FAQ
  contest:
    description: Links to the contest page
  member:
    description: Links to the Member page
  tempperm:
    description: nothing